export enum AuditEvent {
  NOTIFICATION_CREATED = 'NOTIFICATION_CREATED',
  NOTIFICATION_QUEUED = 'NOTIFICATION_QUEUED',
  NOTIFICATION_PROCESSING = 'NOTIFICATION_PROCESSING',
  NOTIFICATION_SENT = 'NOTIFICATION_SENT',
  NOTIFICATION_FAILED = 'NOTIFICATION_FAILED',
  NOTIFICATION_RETRYING = 'NOTIFICATION_RETRYING',
  NOTIFICATION_DEAD_LETTERED = 'NOTIFICATION_DEAD_LETTERED',
  NOTIFICATION_CANCELLED = 'NOTIFICATION_CANCELLED',
}

