export enum NotificationType {
  OTP = 'OTP',
  ORDER_CONFIRMATION = 'ORDER_CONFIRMATION',
  PAYMENT_SUCCESS = 'PAYMENT_SUCCESS',
  PAYMENT_FAILED = 'PAYMENT_FAILED',
  PASSWORD_RESET = 'PASSWORD_RESET',
  MARKETING = 'MARKETING',
  SYSTEM_ALERT = 'SYSTEM_ALERT',
}

