FROM node:20-alpine AS builder

WORKDIR /app
COPY package*.json ./
COPY tsconfig*.json ./
COPY nest-cli.json ./
COPY prisma.config.ts ./
COPY prisma ./prisma/
RUN npm ci

COPY apps/api-gateway ./apps/api-gateway
COPY libs ./libs

RUN npx prisma generate
RUN npm run build:api-gateway

FROM node:20-alpine AS runner
WORKDIR /app
ENV NODE_ENV=production
COPY package*.json ./
RUN npm ci --omit=dev

COPY --from=builder /app/dist/apps/api-gateway ./dist/apps/api-gateway
COPY --from=builder /app/dist/libs ./dist/libs
COPY --from=builder /app/generated ./generated

EXPOSE 3000
CMD ["node", "dist/apps/api-gateway/main.js"]

