FROM node:20-alpine AS builder

WORKDIR /app
COPY package*.json ./
COPY tsconfig*.json ./
COPY nest-cli.json ./
COPY prisma.config.ts ./
COPY prisma ./prisma/
RUN npm ci

COPY apps/scheduler ./apps/scheduler
COPY libs ./libs

RUN npx prisma generate
RUN npm run build:scheduler

FROM node:20-alpine AS runner
WORKDIR /app
ENV NODE_ENV=production
COPY package*.json ./
RUN npm ci --omit=dev

COPY --from=builder /app/dist/apps/scheduler ./dist/apps/scheduler
COPY --from=builder /app/dist/libs ./dist/libs
COPY --from=builder /app/generated ./generated

CMD ["node", "dist/apps/scheduler/main.js"]

